# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33da2324e84f6d9325d263a1e2d4fe07345eff311de450b99c4c2339979105b96d02292526433ba778d10913851fc5919fa0777e57e9814425b016921e478c6a

test:
  secret_key_base: ea97e73600998138c93eb6e9325cfef209371fc02a4ddfdef600800a40bab34070cc05489a1f75d24d77e3bf3b913cebcfc1775235a4709a8d9c303aba1d4851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
